image: localhost:5000/ubuntu-loaded

stages:
  - init
  - injectversion
  - build

init-job:
  stage: init
  script:
    - sh init.sh
    
inject-version-job:
  stage: injectversion
  script:
    - sh inject-version.sh
    
build-job:
  stage: build
  script:
    - sh build-all.sh
    
